### ISSUE TITLE
Please upload the presentation files of the Polyglot Programming course

### ISSUE THREAD

**Issue by ashishnegi** [maruthirj/training#4]
Please upload the presentation files of the Polyglot Programming course.

**Comment by maruthirj** [comment]
Sorry for the delay. Its uploaded now. Let me know if I missed out something.

```
  From: ASHISH NEGI <notifications@github.com>
```

 To: maruthirj/training training@noreply.github.com 
 Sent: Monday, November 2, 2015 12:52 PM
 Subject: [training] Please upload the presentation files of the Polyglot Programming course (#4)

Please upload the presentation files of the Polyglot Programming course.—
